### PR TITLE
xCAT documentation skeleton

### PR DESCRIPTION
**Pull request by whowutwut**
Continue creating the skeleton following @daniceexi 's pull request #14. 

The following commits add skeleton sections for:
* overview
* hardware_management
* help

I also changed based on the comments from #14, after I merged the changes to keep work moving along in the U.S hours.

### CODE REVIEW

**Comment by whowutwut** [comment]
@daniceexi , you can pull in the changes using the "command line instructions, to a temp branch, then run "make html" to see the changes.  That is a lot easier to review than just looking at the RST files.

**Comment by whowutwut** [comment]
Oh yea. Now this one has conflicts because of the latest commit.

**Comment by whowutwut** [comment]
How should we resolve this? I'd like to merge this in so that you can keep working on the outline today...

**Comment by daniceexi** [comment]
I am seeing that I should roll back my change

**Comment by whowutwut** [comment]
Right, or I need to update and commit with your changes..

**Comment by daniceexi** [comment]
@whowutwut It looks hard to resolve the conflict. We have two choices:
1. Merge your change manually. But it's also will be tough to handle the conflict since both of us changed same files.
2. you create another branch base on current xcat-doc master and cherry-pick your another three commits and make a new pull request.

**Comment by daniceexi** [comment]
Sorry for the inconvenience

**Comment by whowutwut** [comment]
sure, no problem, let me see if i can resolve it

**Comment by whowutwut** [comment]
Ok, I merged the changes from commit ef2e8f33e7e7e55585cd3515407a8a4d4a343b1d , seems to be okay to merge clean now :-)

**Pull request merged**
