### PR TITLE
Merge in documentation for Large Cluster Support

### PR DESCRIPTION
**Pull request by whowutwut**
This work is not 100% complete but there's a large chunk of data already written. 
I'd like to get the teams feedback and maybe open another Issue to complete it. 

Regarding xcat2/xcat-doc#5

### CODE REVIEW

**Comment by daniceexi** [comment]
The doc change is a little hard to review! So I can only review it roughly.

Except one comment to c0464e2, I agree to check in this pull request.

BTW, do you know how to refer to a commit in comment?

**Comment by whowutwut** [comment]
@daniceexi , Thanks for trying to review.  The reason I also decided to merge this is because the work was getting too large. I looked at the changes and it was really difficult to review it...

**Comment by whowutwut** [comment]
Going to merge these changes in to keep moving forward.  Additional comments can be made and issues created to address...

**Comment by daniceexi** [comment]
OK, no problem. Please do the merge.

**Comment by whowutwut** [comment]
@daniceexi When you say reference a commit in a comment, you can just write the commit number, then preview, and it will auto create: Ex: 30cb9f01009cee3c03f311b20cd133c509772009  , it looks like you already did it above.

**Pull request merged**
